ci 글자 깨짐 수정

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,6 +9,7 @@ on:
       - "identity-team-account/**"
       - "prod-team-account/**"
       - "dev-team-account/**"
+      - "security-team-account/**"
       - "stage-team-account/**"
 
 permissions:
@@ -43,8 +44,10 @@ jobs:
             ["identity-team-account"]="ROLE_ARN_IDENTITY"
             ["prod-team-account"]="ROLE_ARN_PROD"
             ["dev-team-account"]="ROLE_ARN_DEV"
+            ["security-team-account"]="ROLE_ARN_SECURITY"
             ["stage-team-account"]="ROLE_ARN_STAGE"
-              )
+            ["management-team-account"]="ROLE_ARN_MANAGEMENT"
+          )
 
           TMP_FILE=$(mktemp)
 
@@ -157,41 +160,15 @@ jobs:
 
           PLAN_FILE=tfplan.binary
           PLAN_TXT=plan.txt
+          PLAN_JSON=plan.json
 
-          # 기본 실패 메시지
-          PLAN_CONTENT="Terraform plan failed."
+          terraform plan -no-color -out=$PLAN_FILE || echo "PLAN_FAILED=true" >> $GITHUB_ENV
+          terraform show -no-color $PLAN_FILE > $PLAN_TXT || echo "Plan failed" > $PLAN_TXT
+          terraform show -json $PLAN_FILE > $PLAN_JSON || true
 
-          # Terraform Plan 실행
-          if terraform plan -no-color -out=$PLAN_FILE; then
-            echo "[INFO] terraform plan succeeded."
-            
-            # show 및 no change 여부 판단
-            terraform show -no-color $PLAN_FILE > $PLAN_TXT
-
-            IS_EMPTY=$(terraform show -json $PLAN_FILE 2>/dev/null | jq -e '.resource_changes == []' 2>/dev/null || echo "false")
-
-            if [ "$IS_EMPTY" = "true" ]; then
-              PLAN_CONTENT="(plan success) No changes to apply. Everything looks good!"
-            else
-              # 길이 제한 없이 전체 내용 출력 (출력 너무 클 경우 GitHub가 거부할 수 있음 — 감수한 상태)
-            PLAN_CONTENT=$(
-              cat $PLAN_TXT | \
-              sed 's/`/\\`/g' | \
-              sed 's/::/%::%/g' | \
-              tr -d '\r' | \
-              sed -r "s/\x1B\[[0-9;]*[JKmsu]//g"
-            )
-          fi
-          else
-            echo "[ERROR] terraform plan failed. Skipping show."
-            echo "Terraform plan failed." > $PLAN_TXT
-          fi
-
-          {
-            echo "PLAN_CONTENT<<EOF"
-            echo "$PLAN_CONTENT"
-            echo "EOF"
-          } >> "$GITHUB_OUTPUT"
+          echo "PLAN_CONTENT<<EOF" >> $GITHUB_OUTPUT
+          cat $PLAN_TXT >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
         working-directory: ${{ matrix.dir }}
 
       - name: Comment Terraform Plan on PR
